image: ayberkt/agda:v1

before_script:
  - cd code

test:
  script:
  - ./check.sh

pages:
  script:
  - ./mark-version.sh Main.agda
  - agda --html Main.agda
  - mv html/Main.html html/index.html
  - mv html ../public
  artifacts:
    paths:
    - public
