image: ayberkt/agda:v3

before_script:
  - cd code

test:
  script:
  - agda --version
  - agda Nucleus.agda

cosmetics:
  script:
  - export LC_ALL=C.UTF-8
  - ./check_cosmetics.py TreeType.lagda.md
  - ./check_cosmetics.py HITCoverage.lagda.md
