image: ayberkt/agda:v4

before_script:
  - cd code

test:
  script:
  - agda --version
  - agda --safe Main.lagda.md

pages:
  script:
  - make
  - mv html ../public
  artifacts:
    paths:
    - public

cosmetics:
  script:
  - export LC_ALL=C.UTF-8
  - ./check_cosmetics.py TreeType.lagda.md
  - ./check_cosmetics.py HITCoverage.lagda.md
  - ./check_cosmetics.py CoverFormsNucleus.lagda.md
  - ./check_cosmetics.py Nucleus.agda
  - ./check_cosmetics.py Poset.lagda.md
