image: ayberkt/agda:v3

before_script:
  - cd code

test:
  script:
  - agda --version
  - agda Report.lagda.md

pages:
  script:
  - make
  - mv html/TreeType.html html/index.html
  - mv html ../public
  artifacts:
    paths:
    - public

cosmetics:
  script:
  - export LC_ALL=C.UTF-8
  - ./check_cosmetics.py TreeType.lagda.md
