image: ayberkt/agda:v12

before_script:
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - cd code

test:
  script:
  - agda --version
  - agda --safe Main.lagda.md

pages:
  only:
  - master
  script:
  - make
  - mv html ../public
  artifacts:
    paths:
    - public

cosmetics:
  script:
  - export LC_ALL=C.UTF-8
  - ./check_cosmetics.py FormalTopology.agda
  - ./check_cosmetics.py HITCoverage.lagda.md
  - ./check_cosmetics.py CoverFormsNucleus.lagda.md
  - ./check_cosmetics.py Nucleus.agda
  - ./check_cosmetics.py Poset.lagda.md
  - ./check_cosmetics.py SnocList.agda
  - ./check_cosmetics.py CantorSpace.lagda.md
  - ./check_cosmetics.py ProductTopology.agda
