image: ayberkt/agda:v14

before_script:
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - cd code

test:
  script:
  - agda --version
  - agda --safe Main.lagda.md

pages:
  only:
  - master
  script:
  - ./mark_version.sh CantorSpace.lagda.md
  - make
  - make release.tar
  - mv html ../public
  - mv release.tar ../public/release.tar
  artifacts:
    paths:
    - public

cosmetics:
  script:
  - export LC_ALL=C.UTF-8
  - ./check_cosmetics.py
