image: ayberkt/agda:v2

before_script:
  - cd code

test:
  script:
  - agda --version
  - ./check.sh

pages:
  script:
  - ./mark_version.sh Main.agda
  - agda --html Main.agda
  - mv html/Main.html html/index.html
  - mv html ../public
  artifacts:
    paths:
    - public

cosmetics:
  script:
  - export LC_ALL=C.UTF-8
  - ./check_cosmetics.py TreeType.lagda.md
