* Misc
** Investigate the following remark by Abramsky further (from his PhD thesis).

   #+BEGIN_SRC markdown
    Scott has shown how the theory can be based on elementary, and finitary,
    set-theoretic representations, which in the case of information systems are
    deliberately suggestive of proof theory.
   #+END_SRC

** Ideas
   - The thing that is to a non-deterministic pushdown automaton what a Büchi automaton
     is to a finite automaton.
** These lectures by André Joyal: https://www.youtube.com/watch?v=Ro8KoFFdtS4&t=891s
* Meetings
** <2019-09-27 Fri>
*** Given a poset, the set of downward-closed subsets forms a frame.
*** Lawvere-Tierney topology.
** <2019-10-04 Fri>
*** Nucleus of a frame: ν : L → L
*** J-closed elements form a frame.
*** Remove the index mono and set requirements from the notion of family-based subset.
** ii
*** _◀_ : D(A) → D(A)
*** U ⊆ ◀ U
*** Thm:
*** Lawvere-Tierney topology: j : Ω → Ω



** <2019-10-23 Wed>
   - Given a in some poset and BCov(a), S ∈ BCov(a) implies S ⊑ a↓.

   - _Locality condition_: if b ≤ a and S ∈ Cov(a) then

          ∃ T ∈ Cov(b). ∀ t ∈ T. ∃ s ∈ S. t ≤ s.

          ⇑ The idea is to require this condition instead of Johstone's meet stability.

          ⇑ This is Dragalin's condition from a paper Thierry did not remember during the
     meeting. He will find it by the meeting on <2019-10-25 Fri>.

   - Sambin's definition starts with semilattices which is not the case in Dragalin's
     definition. When viewed categorically, this corresponds to not requiring the category
     to have pullbacks or something like that.

     | Check out Sketches of An Elephant regarding this. |

   - Start with a coverage that satisfies locality and define the nucleus from that.

   - I will have to truncate the inductively defined coverage relation j_C(V).

   - j_C(V) will be downward-closed.

   - If a ◀ V and a ◀ W then a ◀ (V ∩ W), since it will be truncated:

         | if ∥ a ◀ V ∥ and ∥ a ◀ W ∥ then ∥ a ◀ (V ∩ W) ∥ |

     The fact that the conclusion is a proposition without the truncation means that we
     can get rid of the truncations.

   - A lemma will be required for this: if a ◀ W and a ε V then a ◀ (V ∩ W).

   - V sieve, a ◀ V.

   - "Sieve": categorical notion of downward-closed subset.

     | Check out Mac Lane and Moerdijk for this sort of thing. |

** <2019-11-01 Fri>
   - The second condition is like the reproducibility of experiments. It says something
     along the lines of: when we have more knowledge, we can do at least as many
     experiments as before.
   - `outcome` and `next`, together, define an enumeration of the stages.

** <2019-11-08 Fri>
   - [ ] Prove: simulation ⇒ simulation⋆
   - [ ] Define a binary operation on `Experiment⋆` that given two `Experiment⋆`s,
     produces a new `Experiment⋆` that is a refinement of both.
   - [X] Define a refinement relation expressing when a stump refines another.
   - [X] Prove lemma (1).
   - [ ] Prove lemma (2).
     - The main lemma towards proving that the covering relation is a nucleus.
     - This  is the thing where the conclusion is truncated so we can remove the
       truncations in the hypotheses.
   - NOTE Progressiveness is a property (is propositional) whereas simulation is a
     structure (it has non-trivial homotopy structure).
   - Once these have been done, give an example of a discipline that is a distributive
     bounded lattice (Stone space) (as Thierry exemplified on the board).
   - The Fan Theorem in fact says: "the Cantor space has enough points".
